# Generated by Django 4.2.4 on 2023-08-27 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "parcel_serial_number",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "New"),
                            ("2", "Placed"),
                            ("3", "Given"),
                            ("4", "Refusal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("length", models.IntegerField(blank=True)),
                ("width", models.IntegerField(blank=True)),
                ("weight", models.IntegerField(blank=True)),
                ("arrival_from", models.CharField(max_length=100)),
                ("destination_to", models.CharField(max_length=100)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
