# Generated by Django 4.2.4 on 2023-08-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordersapp", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="length",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="weight",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="width",
            field=models.IntegerField(),
        ),
    ]
