# Generated by Django 4.2.4 on 2023-08-27 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ordersapp", "0003_alter_order_length_alter_order_weight_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-time_update"]},
        ),
        migrations.AlterField(
            model_name="order",
            name="length",
            field=models.IntegerField(verbose_name="Length, cm"),
        ),
        migrations.AlterField(
            model_name="order",
            name="parcel_serial_number",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="weight",
            field=models.IntegerField(verbose_name="Weight, kg"),
        ),
        migrations.AlterField(
            model_name="order",
            name="width",
            field=models.IntegerField(verbose_name="Width, cm"),
        ),
    ]
