# Generated by Django 4.2.4 on 2023-08-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordersapp", "0004_alter_order_options_alter_order_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
